version: '3.8'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=password'
    restart: always
  app: &app
    build:
     context: .
     dockerfile: Dockerfile
    container_name: hotspring_app
    volumes:
        - ./:/app
    command: sh -c 'rm -f tmp/pids/server.pid && bin/rails s -b 0.0.0.0'
    ports:
      - '3000:3000'
    tty: true
    stdin_open: true
    depends_on:
      - db
    restart: always
    environment:
      WEBPACKER_DEV_SERVER_HOST: webpacker
  webpacker:
    depends_on: 
      - app
    build: .
    environment:
      NODE_ENV: development
      RAILS_ENV: development
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    command: sh -c 'bin/webpack-dev-server'
    ports:
      - '3035:3035'